export const NIFTY_50_SYMBOLS = [
  'RELIANCE', 'TCS', 'HDFCBANK', 'ICICIBANK', 'BHARTIARTL',
  'SBIN', 'INFY', 'L&T', 'ITC', 'HINDUNILVR', 'AXISBANK',
  'BAJFINANCE', 'KOTAKBANK', 'MARUTI', 'SUNPHARMA', 'TITAN',
  'ULTRACEMCO', 'TATASTEEL', 'TATAMOTORS', 'NTPC', 'POWERGRID',
  'M&M', 'ASIANPAINT', 'COALINDIA', 'BAJAJFINSV', 'ADANIENT',
  'ADANIPORTS', 'ONGC', 'HCLTECH', 'HINDALCO', 'WIPRO', 'JSWSTEEL',
  'GRASIM', 'TECHM', 'INDUSINDBK', 'EICHERMOT', 'DIVISLAB',
  'DRREDDY', 'CIPLA', 'APOLLOHOSP', 'TATAELEXSI', 'TATACONSUM',
  'BAJAJ-AUTO', 'BRITANNIA', 'HEROMOTOCO', 'NESTLEIND', 'SHREECEM',
  'BPCL', 'TATAPOWER', 'HDFCLIFE'
];